### ISSUE TITLE
ImportError: No module named confluo.rpc.client

### ISSUE THREAD

**Issue by liuxiaopiao** [ucbrise/confluo#122]
I have run the predefined python script under "confluo/build/pyclient/test/test_rpc_client.py" and met the error "ImportError: No module named confluo.rpc.client".

 I am not familiar with python, could you please help on how to fix this kind of error? Thanks a lot!

**Comment by anuragkh** [comment]
How are you running the test? The test should only be run via `make test`, otherwise you will run into import issues.

**Comment by liuxiaopiao** [comment]
I run it directly. Or the question could be that: if we want to create one python client to load/query data from the daemon,  I copied the code and saved in "test.py" following https://ucbrise.github.io/confluo/quick_start/  like below:
```python
from confluo.rpc.client import RpcClient
client = RpcClient("127.0.0.1", 9090)
from confluo.rpc.storage import StorageMode
schema = """{
  timestamp: ULONG,
  op_latency_ms: DOUBLE,
  cpu_util: DOUBLE,
  mem_avail: DOUBLE,
  log_msg: STRING(100)
}"""
storage_mode = StorageMode.IN_MEMORY
client.create_atomic_multilog("perf_log", schema, storage_mode)
client.set_current_atomic_multilog("perf_log")
client.add_index("op_latency_ms")
client.install_trigger("high_latency_trigger", "max_latency_ms > 1000")
off1 = client.append([100.0, 0.5, 0.9,  "INFO: Launched 1 tasks"])
off2 = client.append([500.0, 0.9, 0.05, "WARN: Server {2} down"])
off3 = client.append([1001.0, 0.9, 0.03, "WARN: Server {2, 4, 5} down"])
```

And then run "python test.py" and then also met the error "ImportError: No module named confluo.rpc.client". Is there any way we can run the python client code correctly to test confluo basic functions? 
Thanks!

**Comment by anuragkh** [comment]
I see. I am assuming you already ran make install.

Can you tell me your output for `python -c "import confluo"`?

**Comment by liuxiaopiao** [comment]
yeah. I have run make install successfully. 
And the output for the command is:
[opc@testmq ~]$ python -c "import confluo"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named confluo

**Comment by anuragkh** [comment]
This is strange; from your install logs in #121 
```
running install
running bdist_egg
running egg_info
writing requirements to confluo.egg-info/requires.txt
writing confluo.egg-info/PKG-INFO
writing top-level names to confluo.egg-info/top_level.txt
writing dependency_links to confluo.egg-info/dependency_links.txt
reading manifest file 'confluo.egg-info/SOURCES.txt'
writing manifest file 'confluo.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/confluo
creating build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/__init__.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/batch.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/client.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/configuration_params.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/constants.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/data_types.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/rpc_service.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/schema.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/storage.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/stream.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/ttypes.py -> build/bdist.linux-x86_64/egg/confluo/rpc
copying build/lib/confluo/rpc/type_conversions.py -> build/bdist.linux-x86_64/egg/confluo/rpc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/batch.py to batch.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/client.py to client.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/configuration_params.py to configuration_params.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/data_types.py to data_types.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/rpc_service.py to rpc_service.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/schema.py to schema.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/storage.py to storage.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/stream.py to stream.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/ttypes.py to ttypes.pyc
byte-compiling build/bdist.linux-x86_64/egg/confluo/rpc/type_conversions.py to type_conversions.pyc
writing byte-compilation script '/tmp/tmpwFcg6T.py'
/usr/bin/python -O /tmp/tmpwFcg6T.py
removing /tmp/tmpwFcg6T.py
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying confluo.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying confluo.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying confluo.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying confluo.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying confluo.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/confluo-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing confluo-0.1.0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/confluo-0.1.0-py2.7.egg
Copying confluo-0.1.0-py2.7.egg to /usr/lib/python2.7/site-packages
confluo 0.1.0 is already the active version in easy-install.pth
Installed /usr/lib/python2.7/site-packages/confluo-0.1.0-py2.7.egg
Processing dependencies for confluo==0.1.0
Searching for thrift==0.11.0
Best match: thrift 0.11.0
Processing thrift-0.11.0-py2.7.egg
thrift 0.11.0 is already the active version in easy-install.pth
Using /home/opc/confluo/build/pyclient/.eggs/thrift-0.11.0-py2.7.egg
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file
Using /usr/lib/python2.7/site-packages
Finished processing dependencies for confluo==0.1.0
```

It seems like Confluo is installed in `/usr/lib/python2.7/site-packages/` (please confirm `confluo-0.1.0-py2.7.egg` exists). Are you using a different python version?

**Comment by liuxiaopiao** [comment]
The file is existed.
[opc@testmq ~]$ ls -ltr /usr/lib/python2.7/site-packages/confluo*
-rw-r--r--. 1 root root 96088 Jan  3 10:35 /usr/lib/python2.7/site-packages/confluo-0.1.0-py2.7.egg
[opc@testmq ~]$ python --version
Python 2.7.5
[opc@testmq ~]$ which python
/usr/bin/python

**Comment by anuragkh** [comment]
Can you make sure the output of `python -c "import sys; print(sys.path)"` contains `/usr/lib/python2.7/site-packages/`?

**Comment by liuxiaopiao** [comment]
yeah. It has : 
[opc@testmq ~]$ python -c "import sys; print(sys.path)"
['', '/usr/lib/python2.7/site-packages/confluo-0.1.0-py2.7.egg', '/home/opc/confluo/build/pyclient/.eggs/thrift-0.11.0-py2.7.egg', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']

**Comment by anuragkh** [comment]
Strange. Can you add execute permissions, and change ownership of the egg file to your current user (`opc` instead of `root`)?

If that doesn't work, try installing using pip:

```bash
cd build/pyclient
pip install -e . --user --verbose
```
where `build` is the Confluo build directory.

**Comment by liuxiaopiao** [comment]
After adding execution permission for confluo-0.1.0-py2.7.egg, I can only run python client under /home/opc/confluo/build/pyclient. in other folders, if I run the python client, it will report similar error such like "No module named confluo.rpc.client"
```
[opc@testmq pyclient]$ pwd
/home/opc/confluo/build/pyclient
[opc@testmq pyclient]$ python test.py
INFO:confluo.rpc.client:Connecting to 127.0.0.1:9090
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.create_atomic_multilog("perf_log", schema, storage_mode)
  File "/home/opc/confluo/build/pyclient/confluo/rpc/client.py", line 75, in create_atomic_multilog
    self.cur_m_id_ = self.client_.create_atomic_multilog(name, rpc_schema, storage_mode)
  File "/home/opc/confluo/build/pyclient/confluo/rpc/rpc_service.py", line 303, in create_atomic_multilog
    return self.recv_create_atomic_multilog()
  File "/home/opc/confluo/build/pyclient/confluo/rpc/rpc_service.py", line 329, in recv_create_atomic_multilog
    raise result.ex
confluo.rpc.ttypes.rpc_management_exception: rpc_management_exception(msg=u'Table perf_log already exists.')
[opc@testmq pyclient]$ cd ..
[opc@testmq build]$ pwd
/home/opc/confluo/build
[opc@testmq build]$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from confluo.rpc.client import RpcClient
ImportError: No module named confluo.rpc.client
```

**Comment by anuragkh** [comment]
Did you try changing ownership:

```bash
sudo chown opc:opc /usr/lib/python2.7/site-packages/confluo-0.1.0-py2.7.egg
```

Also, did you try running `pip install -e . --user --verbose` under `/home/opc/confluo/build/pyclient`?

**Comment by liuxiaopiao** [comment]
I run the pip install:
```
[opc@testmq pyclient]$ pip install -e . --user --verbose
Obtaining file:///home/opc/confluo/build/pyclient
  Running setup.py (path:/home/opc/confluo/build/pyclient/setup.py) egg_info for package from file:///home/opc/confluo/build/pyclient
    Running command python setup.py egg_info
    running egg_info
    writing requirements to confluo.egg-info/requires.txt
    error: confluo.egg-info/requires.txt: Permission denied
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /home/opc/confluo/build/pyclient/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 307, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 489, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/opc/confluo/build/pyclient/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 301 122
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching permanant redirect
Looking up "https://pypi.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
"GET /pypi/pip/json HTTP/1.1" 200 16411
Updating cache with response from "https://pypi.org/pypi/pip/json"
Caching due to etag
You are using pip version 8.1.2, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by liuxiaopiao** [comment]
Oh i should add sudo before the command. now it works
```
[opc@testmq pyclient]$ sudo pip install -e . --user --verbose
Obtaining file:///home/opc/confluo/build/pyclient
  Running setup.py (path:/home/opc/confluo/build/pyclient/setup.py) egg_info for package from file:///home/opc/confluo/build/pyclient
    Running command python setup.py egg_info
    running egg_info
    writing requirements to confluo.egg-info/requires.txt
    writing confluo.egg-info/PKG-INFO
    writing top-level names to confluo.egg-info/top_level.txt
    writing dependency_links to confluo.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'confluo.egg-info/SOURCES.txt'
    writing manifest file 'confluo.egg-info/SOURCES.txt'
  Source in /home/opc/confluo/build/pyclient has version 0.1.0, which satisfies requirement confluo==0.1.0 from file:///home/opc/confluo/build/pyclient
Requirement already satisfied (use --upgrade to upgrade): thrift>=0.10.0 in ./.eggs/thrift-0.11.0-py2.7.egg (from confluo==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.2 in /usr/lib/python2.7/site-packages (from thrift>=0.10.0->confluo==0.1.0)
Installing collected packages: confluo
  Running setup.py develop for confluo
    Running command /usr/bin/python2 -c "import setuptools, tokenize;__file__='/home/opc/confluo/build/pyclient/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --user --prefix=
    running develop
    running egg_info
    writing requirements to confluo.egg-info/requires.txt
    writing confluo.egg-info/PKG-INFO
    writing top-level names to confluo.egg-info/top_level.txt
    writing dependency_links to confluo.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'confluo.egg-info/SOURCES.txt'
    writing manifest file 'confluo.egg-info/SOURCES.txt'
    running build_ext
    Creating /root/.local/lib/python2.7/site-packages/confluo.egg-link (link to .)
    Adding confluo 0.1.0 to easy-install.pth file

    Installed /home/opc/confluo/build/pyclient
Successfully installed confluo-0.1.0
Cleaning up...
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 301 122
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching permanant redirect
Looking up "https://pypi.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
"GET /pypi/pip/json HTTP/1.1" 200 16411
Updating cache with response from "https://pypi.org/pypi/pip/json"
Caching due to etag
You are using pip version 8.1.2, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by liuxiaopiao** [comment]
Close the ticket and thanks @anuragkh  a lot

**Comment by jjproe** [comment]
I installed and tested confluo a few days ago, and run in the same problem: error on importing confluo..
The solution described above, has not working for me.

I changed _packages_ in **setup.py** -> from packages=['confluo.rpc'] to packages=['confluo', 'confluo.rpc']
Execute python setup.py bdist_egg and copy this to my /usr/local/lib/python2.7/dist-packages... 
Now python always found him... 
Greetings.
